name: afternoon
on:
  schedule:
  - cron:  '20 4 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send afternoon to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./good_afternoon.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_AFTERNOON_ID: ${{ secrets.TEMPLATE_AFTERNOON_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY_ZXX: ${{ secrets.BIRTHDAY_ZXX }}
      BIRTHDAY_WXH: ${{ secrets.BIRTHDAY_WXH }}
      CITY: ${{ secrets.CITY }}
